/** Analytics service layer — domain-driven re-exports. */
export {
  normalizeTrade,
  normalizeTrades,
  exitEvents,
  allExitEvents,
  buildTimeRange,
  filterTradesByRange,
  inRange,
  TIME_RANGE_LABELS,
  buildEquityCurve,
  buildPortfolioTimeline,
  buildDrawdownSeries,
  summarizeDrawdown,
  summarizeAnalytics,
  realizedTrades,
  EMPTY_ANALYTICS_SUMMARY,
  aggregateByTag,
  topPerformingTags,
  worstPerformingTags,
  buildEmotionalAnalytics,
  buildDisciplineAnalytics,
  formatPercent,
  formatRatio,
  formatRMultiple,
  formatDuration,
} from "@/lib/analytics";
