/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWeeklyReviewRouteImport } from './routes/_app.weekly-review'
import { Route as AppTradesRouteImport } from './routes/_app.trades'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppJournalTimelineRouteImport } from './routes/_app.journal-timeline'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCapitalRouteImport } from './routes/_app.capital'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAddTradeRouteImport } from './routes/_app.add-trade'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeeklyReviewRoute = AppWeeklyReviewRouteImport.update({
  id: '/weekly-review',
  path: '/weekly-review',
  getParentRoute: () => AppRoute,
} as any)
const AppTradesRoute = AppTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalTimelineRoute = AppJournalTimelineRouteImport.update({
  id: '/journal-timeline',
  path: '/journal-timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCapitalRoute = AppCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAddTradeRoute = AppAddTradeRouteImport.update({
  id: '/add-trade',
  path: '/add-trade',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/add-trade': typeof AppAddTradeRoute
  '/analytics': typeof AppAnalyticsRoute
  '/capital': typeof AppCapitalRoute
  '/dashboard': typeof AppDashboardRoute
  '/journal-timeline': typeof AppJournalTimelineRoute
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
  '/today': typeof AppTodayRoute
  '/trades': typeof AppTradesRoute
  '/weekly-review': typeof AppWeeklyReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/add-trade': typeof AppAddTradeRoute
  '/analytics': typeof AppAnalyticsRoute
  '/capital': typeof AppCapitalRoute
  '/dashboard': typeof AppDashboardRoute
  '/journal-timeline': typeof AppJournalTimelineRoute
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
  '/today': typeof AppTodayRoute
  '/trades': typeof AppTradesRoute
  '/weekly-review': typeof AppWeeklyReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/add-trade': typeof AppAddTradeRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/capital': typeof AppCapitalRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/journal-timeline': typeof AppJournalTimelineRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/trades': typeof AppTradesRoute
  '/_app/weekly-review': typeof AppWeeklyReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/add-trade'
    | '/analytics'
    | '/capital'
    | '/dashboard'
    | '/journal-timeline'
    | '/portfolio'
    | '/settings'
    | '/today'
    | '/trades'
    | '/weekly-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/add-trade'
    | '/analytics'
    | '/capital'
    | '/dashboard'
    | '/journal-timeline'
    | '/portfolio'
    | '/settings'
    | '/today'
    | '/trades'
    | '/weekly-review'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/add-trade'
    | '/_app/analytics'
    | '/_app/capital'
    | '/_app/dashboard'
    | '/_app/journal-timeline'
    | '/_app/portfolio'
    | '/_app/settings'
    | '/_app/today'
    | '/_app/trades'
    | '/_app/weekly-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weekly-review': {
      id: '/_app/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof AppWeeklyReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trades': {
      id: '/_app/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AppTradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal-timeline': {
      id: '/_app/journal-timeline'
      path: '/journal-timeline'
      fullPath: '/journal-timeline'
      preLoaderRoute: typeof AppJournalTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capital': {
      id: '/_app/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof AppCapitalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add-trade': {
      id: '/_app/add-trade'
      path: '/add-trade'
      fullPath: '/add-trade'
      preLoaderRoute: typeof AppAddTradeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddTradeRoute: typeof AppAddTradeRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCapitalRoute: typeof AppCapitalRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJournalTimelineRoute: typeof AppJournalTimelineRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppTradesRoute: typeof AppTradesRoute
  AppWeeklyReviewRoute: typeof AppWeeklyReviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddTradeRoute: AppAddTradeRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCapitalRoute: AppCapitalRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJournalTimelineRoute: AppJournalTimelineRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodayRoute: AppTodayRoute,
  AppTradesRoute: AppTradesRoute,
  AppWeeklyReviewRoute: AppWeeklyReviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
